name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: one-line script
        run: eecho "Hello, world!"
      - name: multiline script
        run: |
          node -v
          npm -v