name: shell commands

on:
  schedule:
    - cron: '*/2****'

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: multiline script
        run: |
          node -v
          npm -v