name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: one-line script
        run: echo "Hello, world!"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: multiline script
        run: |
          import platform
          print(platform.processor())
        shell: python